branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: portfolio-light-local
  branch: null
  default_ec2_keyname: portfolio-ui-server
  default_platform: Multi-container Docker running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
